---
- hosts: all
  gather_facts: false
  connection: local

  tasks:

    - name: display production password
      debug:
        var: "{{ production }}"

    - name: display development password
      debug:
        var: "{{ development }}"
